<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use League\OAuth2\Client\Provider\Google;

class GoogleDriveController extends Controller
{
    public function redirect()
    {
        $provider = new Google([
            'clientId'     => env('GOOGLE_CLIENT_ID'),
            'clientSecret' => env('GOOGLE_CLIENT_SECRET'),
            'redirectUri'  => env('GOOGLE_REDIRECT_URI'),
        ]);

        // define the scopes
        $options = [
            'scope' => [
                'https://www.googleapis.com/auth/drive'
            ],
            'access_type' => 'offline', // to get a refresh token
            'prompt' => 'consent' // to force the consent screen and get a refresh token every time
        ];

        $authorizationUrl = $provider->getAuthorizationUrl($options);

        // Store the state generated by the provider
        session(['oauth2state' => $provider->getState()]);

        // Redirect the user to the authorization URL
        return redirect()->away($authorizationUrl);
    }

    public function callback(Request $request)
    {
        $provider = new Google([
            'clientId'     => env('GOOGLE_CLIENT_ID'),
            'clientSecret' => env('GOOGLE_CLIENT_SECRET'),
            'redirectUri'  => env('GOOGLE_REDIRECT_URI'),
        ]);

        if (!empty($request->get('error'))) {
            // Got an error, probably user denied access
            return redirect('/')->with('error', 'Google API Error: ' . htmlspecialchars($request->get('error'), ENT_QUOTES, 'UTF-8'));
        } elseif (empty($request->get('code'))) {
            // If we don't have an authorization code then get one
            return redirect()->action([self::class, 'redirect']);
        } elseif (empty($request->get('state')) || ($request->get('state') !== session('oauth2state'))) {
            // State is invalid, possible CSRF attack in progress
            session()->forget('oauth2state');
            return redirect('/')->with('error', 'Invalid state');
        } else {
            try {
                // Try to get an access token using the authorization code grant.
                $token = $provider->getAccessToken('authorization_code', [
                    'code' => $request->get('code')
                ]);

                // We got an access token, let's now get the owner details
                $ownerDetails = $provider->getResourceOwner($token);

                // For now, let's just dump the token and owner details
                // In a real app, you would store the refresh token securely
                // associated with the user.
                $refreshToken = $token->getRefreshToken();
                
                $authUser = auth()->user();

                if ($authUser) {
                    $authUser->update([
                        'google_access_token' => $token->getToken(),
                        'google_refresh_token' => $refreshToken ?? $authUser->google_refresh_token, // Persist existing refresh token if new one is not provided
                        'google_token_expires_at' => now()->addSeconds($token->getExpires()),
                        'google_email' => $ownerDetails->getEmail(),
                    ]);
                } else {
                    // Handle case where user is not authenticated, maybe redirect to login
                    return redirect('/')->with('error', 'User not authenticated.');
                }

                return redirect('/')->with('success', 'Successfully authenticated with Google!');

            } catch (\Exception $e) {
                // Failed to get access token
                return redirect('/')->with('error', 'Something went wrong: ' . $e->getMessage());
            }
        }
    }
}
